
// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
//  response.send("Hello from Firebase!");
// });
'use strict';

// The Cloud Functions for Firebase SDK to create Cloud Functions and setup triggers.
const functions = require('firebase-functions');
const {actionssdk} = require('actions-on-google');
const app = actionssdk({debug: true});

app.intent('actions.intent.MAIN', (conv) => {
    return conv.ask('<speak>' + ' Hello there.<break time="1"/> ' +
    ' Say the name of two characters from Marvel or DC and find out who\'s gonna win. Or you can get intel on any character of your choice and know where he stand in this ladder of Almighties.</speak>');
});

app.intent('actions.intent.TEXT', (conv, input) => {
    var characters = [["abomination", "Abomination", "marvel", "30", "Formerly known as Emil Blonsky, a spy of Soviet Yugoslavian origin working for the KGB, the Abomination gained his powers after receiving a dose of gamma radiation similar to that which transformed Bruce Banner into the incredible Hulk. "],
["adam warlock", "Adam Warlock", "marvel", "78", "Emerging from a cocoon, the being known as Adam Warlock defies his creators' intentions and proves to be an important cosmic entity. Created by the Enclave to be part of a race of super humans who would abolish war, illness, and crime, Adam Warlock is a unique being who uses his immense and formidable powers to safeguard the universe."],
["ancient one", "Ancient One", "marvel", "72", "The youth who would eventually be called the Ancient One was born over five hundred years ago in Kamar-Taj, a village in a hidden land in the Himalaya Mountains in the area now known as Tibet. He became the first Sorcerer Supreme and was able to keep Dormammu out of Earth Dimension for 5 centuries."],
["anti monitor", "Anti Monitor", "dc", "92", "The Anti-Monitor is a supervillain from Crisis on Infinite Earths. He is The Monitor’s counterpart from The Anit-Matter Universe and was the sole Guardian of The Sinestro Corps. "],
["antman", "Antman", "marvel", "18", "Ex-con Scott Lang uses high-tech equipment to shrink down to insect-size and fight injustice as Ant-Man."],
["apocalypse", "Apocalypse", "marvel", "59", "Approximately 5,000 years old, Apocalypse is a virtually immortal mutant. His real name En Sabah Nur translates to The First One."],
["apollo", "Apollo", "dc", "44", "Like Superman, Apollo's powers are dependent on the sun. His body behaves like a battery, absorbing sunlight and converting it into energy he can use. Without exposure to the sun his strength, resilience, and ability to fly diminish, ultimately to the point of disappearing—a concern, since aboard the Carrier he is often out of direct sunlight. Apollo is cast in the mould of the Superman archetype.  Apollo is notable for being among the first openly gay superheroes in print, although several years behind Marvel Comics' Northstar.[1] He married fellow The Authority member Midnighter and both adopted Jenny Quantum."],
["aquaman", "Aquaman", "dc", "42", "Monarch of the undersea realm of Atlantis and King of the Seven Seas, Aquaman is one of the most powerful DC Super Heroes—commanding a kingdom that covers three-quarters of the Earth’s surface, including all the creatures contained within."],
["ares", "Ares", "dc", "50", "An immortal being who draws his power from belief and conflict, Ares was worshipped by many on Earth as a god of Olympus."],
["bane", "Bane", "dc", "3", "Raised in a prison on the island of Santa Prisca for the crimes of his father, Bane dedicated his life to honing his mind and body into a perfect weapon."],
["batgirl", "Batgirl", "dc", "3", "Barbara Gordon redefined what it meant to be a self-made hero when she crafted her own costume and joined Batman's crusade right under her father’s nose."],
["batman", "Batman", "dc", "46", "Bruce Wayne wages eternal war on the criminals of Gotham City. He is vengeance. He is the night. He is Batman."],
["beast", "Beast", "marvel", "10", "Henry McCoy was a genius. He became one of Apocalypse's leading scientists and spent his time working on expanding genetic mutation alongside his mentor, Nathan Essex, the man known as Sinister."],
["beast boy", "Beast Boy", "dc", "11", "Able to take the form of almost any animal, Garfield Logan, despite his flippant personality, is one of the most esteemed superheroes to bear the name “Titan.”"],
["beyonder", "Beyonder", "marvel", "98", "A near omnipotent and vastly powerful mutant inhuman. He is the most powerful being in the Marvel multiverse second alone to The One Above All. He was so strong, that all the Marvel abstracts (such as Eternity, Infinity and Death), supreme cosmic beings (such as Galactus and the Stranger), and The Living Tribunal himself were left at his mercy."],
["big brada", "Big Brada", "dc", "38", "Taken from her mother at an early age, Barda grew up on Apokolips in Granny Goodness's \"Orphanage\" where she was trained in the art of battle. Barda relished fighting and enjoyed besting anyone that challenged her."],
["black adam", "Black Adam", "dc", "75", "One of the world’s foremost wielders of magic equal of Shazam, Black Adam has been both hero and villain over a life that’s spanned thousands of years."],
["black canary", "Black Canary", "dc", "2", "Fearless street fighter and frequent partner to Green Arrow, Dinah Lance tackles injustice with her unmatched martial arts skills and her ear-piercing \"Canary Cry\"."],
["black panther", "Black Panther", "marvel", "47", "T’Challa is the king of the secretive and highly advanced African nation of Wakanda - as well as the powerful warrior known as the Black Panther. He protects his people as the latest in a legacy line of Black Panther warriors."],
["black widow", "Black Widow", "marvel", "3", "Despite super spy Natasha Romanoff’s checkered past, she’s become one of S.H.I.E.L.D.’s most deadly assassins and a frequent member of the Avengers. Trusted by some and feared by most, the Black Widow strives to make up for the bad she had done in the past by helping the world, even if that means getting her hands dirty in the process."],
["cable", "Cable", "marvel", "2", "Cable was sent to the future in a bid to save his life when he was infected by a techno-organic virus. Using his formidable telekinetic abilities and cybernetic enhancements, Cable battles Super Villain foes in his quest for peace."],
["captain america", "Captain America", "marvel", "23", "Recipient of the Super-Soldier serum, World War II hero Steve Rogers fights for American ideals as one of the world’s mightiest heroes and the leader of the Avengers."],
["captain atom", "Captain Atom", "dc", "86", "Captain Atom is a nuclear-powered super-hero. Beginning his career in the military as a member of the U.S. Air Force, he was framed for a crime he did not commit; to avoid a death sentence, he was forced to undergo scientific experimentation. His powers stem from an ability to tap into the quantum field. He has also been a member of the Justice League and the Living Assault Weapons. And yes!! He is more powerful than Dr. Manhattan!"],
["captain cold", "Captain Cold", "dc", "3", "Slowing down the Fastest Man Alive is no easy task, let alone stopping him cold in his tracks. But it’s all in a day’s work for Captain Cold. Cold and calculating. That’s the best way to describe Leonard Snart, and it’s how he approached the job. Get in, get out and if anybody gets in the way, deal with them. No fuss and no muss. It was simple and it worked. At least until a certain scarlet-colored speedster interfered."],
["captain marvel", "Captain Marvel", "marvel", "64", "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Now, returning to Earth years later, she must remember her past in order to to prevent a full invasion by shapeshifting aliens, the Skrulls."],
["carnage", "Carnage", "marvel", "32", "Carnage was once a serial killer known as Cletus Kasady, and became Carnage after merging with the offspring of the alien symbiote called Venom during a prison breakout. The symbiote amplified his psychotic nature making him even less mentally stable than he had been previously, and therefore even more dangerous. An interesting note is that, unlike Venom, Carnage is a singular entity, referring to himself as \"I\" instead of \"We\", because the symbiote has actually merged into Kasady's bloodstream. "],
["charles xavier", "Charles Xavier", "marvel", "58", "Charles Xavier is one of the world's premiere experts on mutants. A mutant telepath, Charles and his wife Moira MacTaggert wrote the book on post-human medicine, treating young mutants endangered by their own powers."],
["colussus", "Colussus", "marvel", "16", "Colossus became leader of the Super Soldiers and faced his brainwashed brother in combat. Now a Horseman of Apocalypse, Mikhail destroyed all of Russia's super heroes except his brother. The severely beaten Colossus chose to dedicate his life to stopping Apocalypse and Mikhail on that day. He left Russia to find the X-Men."],
["constantine", "Constantine", "dc", "9", "Constantine has vowed mastery over the occult and the demonic creatures that seek to abuse its power. But in so doing, he’s also learned the hard truth about what it takes to stand against powerful dark forces—a willingness to sacrifice anything and anyone."],
["cyborg", "Cyborg", "dc", "48", "Part man, part machine, Vic Stone is a former member of the Teen Titans and a current member of the Justice League who wrestles to preserve his humanity with every new upgrade."],
["daredevil", "Daredevil", "marvel", "2", "As a boy, Matt Murdock lost his sight—and gained superhuman senses—in an accident that taught him to live without fear. He went on to study law, leading him to a life of crime fighting in New York; as both a lawyer and as the vigilante Daredevil."],
["dark knight", "Dark Knight", "dc", "46", "Bruce Wayne wages eternal war on the criminals of Gotham City. He is vengeance. He is the night. He is Batman."],
["darkseid", "Darkseid", "dc", "88", "The ruling dictator of the world of Apokolips, Darkseid operates on a scale that terrifyingly dwarfs those of the world's greatest heroes. Darkseid seeks to enslave all life in the universe, reshape existence in his image and exert ultimate control. His desire is to eliminate free will and control everyone so that they bow beneath his feet."],
["deadpool", "Deadpool", "marvel", "29", "Wade Wilson was born in Canada, but grew up to become the least Canadian person ever. When it comes to the Merc with a Mouth, with great power comes no responsibility. Ever-quipping mercenary Deadpool’s healing factor—and big mouth—make him one of the most relentlessly wisecracking heroes in the universe."],
["deadshot", "Deadshot", "dc", "3", "An assassin, expert marksman and lethal DC Universe villain, Floyd Lawton lives by a simple code: do the job that you're hired for with the least amount of casualties possible—after all, you're not being paid to waste bullets."],
["deathstroke", "Deathstroke", "dc", "3", "Never failing—even when it comes to taking down the World’s Greatest Super Heroes, some of the most powerful beings in the world—that’s what makes you the best. That’s what makes you Deathstroke. Beyond his heightened speed, strength, and senses, Deathstroke's greatest asset comes from his incredibly high intelligence, which makes him a master strategist and tactician."],
["docter manhatton", "Docter Manhatton", "dc", "85", "Doctor Jonathan Osterman was a nuclear physicist who was caught in a radioactive particle test, which transformed him into a god-like being known as Doctor Manhattan. He is  a quantum being of nearly unlimited power. Mister Mxyzptlk, a near-omnipotent being in his own right, has stated that Manhattan's power far exceeds his own."],
["docter strange", "Docter Strange", "marvel", "73", "Formerly a renowned surgeon, Doctor Stephen Strange now serves as the Sorcerer Supreme—Earth’s foremost protector against magical and mystical threats. Possessing vast magical knowledge and skills to call upon, he now serves as Earth’s newest Master of the Mystic Arts."],
["doctor octopus", "Doctor Octopus", "marvel", "6", "Otto Octavius designed a set of highly advanced mechanical arms to assist him with his research into atomic physics. The tentacled arms were resistant to radiation and were capable of great strength and highly precise movement. They were attached to a harness that fit around his body.  During an accidental radiation leak that ended in an explosion, the apparatus became fused to Octavius' body. It was later revealed that the radiation (or possibly his own latent mutation) had mutated his brain so that he could control the movement of the arms using his thoughts alone."],
["doomsday", "Doomsday", "dc", "76", "Doomsday was originally created on Krypton as part of a deranged scientist's quest to create the perfect hunter. The creature was subjected to cruel and terrible experiments—killed and cloned thousands upon thousands of times—a process that allowed his body to adapt natural defenses against whatever previously had bested him. No one will ever forget the day that Superman died. Nor will they forget the name of the monster responsible—Doomsday."],
["dormammu", "Dormammu", "marvel", "87", "Originating in the aptly-named Dark Dimension, this incredibly powerful being has ominous plans for Earth and those who live there. He is ruler of Dark Dimension and can use it as a source for infinite energy."],
["dr manhatton", "Dr Manhatton", "dc", "85", "Doctor Jonathan Osterman was a nuclear physicist who was caught in a radioactive particle test, which transformed him into a god-like being known as Doctor Manhattan. He is  a quantum being of nearly unlimited power. Mister Mxyzptlk, a near-omnipotent being in his own right, has stated that Manhattan's power far exceeds his own."],
["dr strange", "Dr Strange", "marvel", "73", "Formerly a renowned surgeon, Doctor Stephen Strange now serves as the Sorcerer Supreme—Earth’s foremost protector against magical and mystical threats. Possessing vast magical knowledge and skills to call upon, he now serves as Earth’s newest Master of the Mystic Arts."],
["drax", "Drax", "marvel", "15", "Drax uses his super strength and combat skills to destroy any enemies of the galaxy. Drax is a brutish, battle-tested warrior. A former intergalactic criminal, Drax has no interest in money, only avenging his slain family. Reluctant at first, the hero with an unquenchable murderous rage joins the Guardians of the Galaxy."],
["eclipso", "Eclipso", "dc", "90", "He is the first incarnation of the Wrath of God and the Angel of Vengeance. Eclipso is sealed inside the Heart of Darkness, which appears as a small, black diamond, first mined on the desolate world of Apokolips."],
["erik killmonger", "Erik Killmonger", "marvel", "46", "Raised in America, the man known as Erik Killmonger returns to his father's home of Wakanda determined to overthrow T'Challa and rule the nation himself. Erik “Killmonger” Stevens challenged the Black Panther for the throne of Wakanda with special ops skills, devious tactics, and an eye on changing the world."],
["eternity", "Eternity", "marvel", "94", "The very embodiment of time. Eternity can manipulate space, time, and reality itself as he wishes. His power is greater even than the likes of Galactus."],
["falcon", "Falcon", "marvel", "5", "When Captain America asked Air Force Veteran Sam Wilson for help, Wilson immediately agreed. He donned the flight suit he’d used in combat to become the Falcon, setting him on a path towards becoming an Avenger."],
["firestorm", "Firestorm", "dc", "45", "When it comes to personalities, Ronnie Raymond and Jason Rusch are on opposite ends of the figurative periodic table. Ronnie’s a good-looking athlete with a quick-to-action attitude and a healthy dose of ego, while Jason’s a gifted science student who’s never happier than when he’s working alone in a lab. Caught in an explosion that should have killed them both, the pair were instead fused together into one nuclear-powered being. Bonded through a phenomenon known as the Firestorm Matrix, Ronnie and Jason act together as a single super hero"],
["flash", "Flash", "dc", "51", "The fastest man alive. Barry Alen not only have super speed but also abilities like time travel. Definitely his power are not limited to speed only."],
["franklin richards", "Franklin Richards", "marvel", "88", "One of the rare omega level mutants, He has the ability to warp reality on a much more massive scale than Proteus. He is quite possibly the strongest mutant to ever exist.  "],
["galactus", "Galactus", "marvel", "83", "One of the strongest in the universe. Eats entire planets, possesses vast knowledge, unlimited cosmic power, and gave beings as strong as the Silver Surfer their power and is still in an entire different power league."],
["gamora", "Gamora", "marvel", "15", "Raised by Thanos to be a living weapon, Gamora seeks redemption as a member of the Guardians of the Galaxy, putting her extraordinary fighting abilities to good use. Gamora is a trained warrior assassin, whose life under her adoptive father Thanos’ torturous wrath leads her to turn against him. Realizing the universe is threatened by powerful Infinity Stones, she takes up the mantle of Guardian of the Galaxy. "],
["ghost rider", "Ghost Rider", "marvel", "36", "Bonded with the demon Zarathos, the motorcycle stunt man Johnny Blaze becomes the feared Ghost Rider, who craves vengeances against the souls of those who would do the world harm in the world."],
["gorilla grodd", "Gorilla Grodd", "dc", "51", "Hailing from the technologically advanced Gorilla City, home to hyper-intelligent primates living in their own secret, secluded society, Grodd stood apart from his fellow simians through his telepathic and telekinetic powers. Grodd has a brutal nature and a level of enhanced strength that make him incredibility dangerous in a physical fight."],
["grandmaster", "Grandmaster", "marvel", "80", "The Grandmaster is an eternal, the same race as the Runner and the Champion. He is vastly intelligent, old, and powerful. He possesses telepathy, and other psionic powers such as telekinesis to a high degree, mind alteration, mind wipe etc."],
["green arrow", "Green Arrow", "dc", "4", "What was the last thing you took home from an island getaway? A tacky souvenir? A great tan? More boring slideshows than you have friends to show?  Spoiled billionaire Oliver Queen came home with an entirely different personality—and a newfound purpose in life."],
["green goblin", "Green Goblin", "marvel", "7", "Norman Osborn is the father of Peter Parker’s best friend Harry – and Spider-Man’s long-time enemy. When Norman became the Green Goblin, he went on a maniacal rampage, forging a battle that continues to stalk Spidey. Norman Osborn's experiments increase his strength but lead to a mental breakdown, as he becomes a cackling, evil presence often driven by a very personal vendetta with Spider-Man."],
["green lantern", "Green Lantern", "dc", "62", "A member of the Green Lantern Corps, armed with power rings fueled by the green energy of all willpower in the universe."],
["groot", "Groot", "marvel", "20", "This sentient alien tree branches out of his comfort zone to help the Guardians of the Galaxy keep the people of the universe safe. You can learn a lot about him when he says “I am Groot”."],
["harley quinn", "Harley Quinn", "dc", "1", "Love makes us do crazy things. And for the bubbly and psychotic Harley Quinn, that includes dressing in costume, becoming a super-villain, carrying gag-themed weaponry, and murdering countless civilians—all just to put a smile on her puddin's face."],
["hawkeye", "Hawkeye", "marvel", "4", "A master marksman and longtime friend of Black Widow, Clint Barton serves as the Avengers’ amazing archer. Clint Barton puts his talents to good use by working for S.H.I.E.L.D. as a special agent. The archer known as Hawkeye also boasts a strong moral compass that at times leads him astray from his direct orders."],
["hawkgirl", "Hawkgirl", "dc", "63", "An immortal warrior who's been reborn into countless lives, Kendra Saunders uses her past to plot a course for a brighter future. Throughout the history of the Multiverse, there has been a line of fierce, winged women who have defended the Earth and gone by the name Hawkgirl."],
["hawkman", "Hawkman", "dc", "63", "Originally hailing from the planet Thanagar, Hawkman is the world's fiercest attacker and one of its most feared warriors. With his wings and his trusty mace, Hawkman patrols the skies with a savage intensity. Hawkman’s weapons and artificial wings both are forged from the mysterious Nth metal, which can only found on his home planet. They grant him the power of flight as well as enhanced strength and healing."],
["heimdall", "Heimdall", "marvel", "35", "Heimdall is the guardian of the Bifrost Bridge, and as its gatekeeper, he controls access and travel between Asgard and the other nine realms. With his all-seeing eyes, Heimdall protects Asgard and all of its citizens."],
["hela", "Hela", "marvel", "69", "Hela, Odin’s first born and sister to the Asgardian princes, seeks her place as the rightful heir of Asgard following the death of Odin and her release from imprisonment. With family ties to the rulers of Asgard, Hela seeks power (and followers) for herself."],
["hercules", "Hercules", "marvel", "61", "Hercules is the son of Zeus, king of the gods of Olympus, and Alcmena, a mortal woman who lived about three thousand years ago. Recognizing the need for a son who would be powerful enough to defend both the Olympian gods and humanity from future dangers he foresaw, Zeus seduced Alcmena in the guise of her husband, King Amphitryon of Troezen."],
["hulk", "Hulk", "marvel", "49", "Dr. Bruce Banner lives a quiet life, until he saves the life of teenager Rick Jones from a gamma bomb explosion. After this, the mild-mannered scientist transforms into a powerful being called the Hulk whenever he gets angry. "],
["human torch", "Human Torch", "marvel", "25", "Johnny Storm yearns for adventure and frequently finds it either with the Fantastic Four, another super group, or by himself. With his fiery form, he can burn through just about any adversity and put a smile on it while he does.  "],
["infinity", "Infinity", "marvel", "94", "Infinity is the cosmic entity that defines the entirety of space and its occupants. Together with Eternity it encompasses all of creation, representing both time and space. Infinity was \"born\", along with the other abstracts, with the \"Big Bang\". Each universe has its own Infinity, all overseen by the Living Tribunal and its enigmatic master, the \"One Above All\"."],
["invisible woman", "Invisible Woman", "marvel", "55", "Susan is the glue that holds the Fantastic Four together. She’s strong-willed, assertive, level-headed, and clever. She also tends to be more diplomatic than the rest of team - preferring to look for peaceful solutions to their conflicts before jumping into a fight."],
["ironman", "Ironman", "marvel", "45", "Genius. Billionaire. Playboy. Philanthropist. Tony Stark's confidence is only matched by his high-flying abilities as the hero called Iron Man."],
["jean grey", "Jean Grey", "marvel", "91", "Jean is possed by Phoenix Force. Phoenix Force is the most feared being in the universe. Single handedly defeated Galactus himself and over powered even the mkraan crystal."],
["john constantine", "John Constantine", "dc", "9", "Constantine has vowed mastery over the occult and the demonic creatures that seek to abuse its power. But in so doing, he’s also learned the hard truth about what it takes to stand against powerful dark forces—a willingness to sacrifice anything and anyone."],
["joker", "Joker", "dc", "14", "Don't make us laugh. The green hair. The crazed smile. The maniacal cackle. You know exactly who he is and how far he'd go to put a smile on your face. Unquestionably the most recognizable and popular comic book villain in pop culture history. Unpredictable, violent and incredibly dangerous, he is chaos personified and has taken on everyone from his archenemy Batman to even the Man of Steel."],
["juggernaut", "Juggernaut", "marvel", "51", "Step-Brother to Charles Xavier, Juggernaut is said to be unstopable once set into motion. Deriving his power from a demon he is one of the strongest character on the Earth."],
["kid flash", "Kid Flash", "dc", "26", "Flash – Fastest man Alive! But this time he is Wally West and a kid."],
["killer frost", "Killer Frost", "dc", "13", "After gaining the ability to absorb heat from living beings and to project cold and ice, Caitlin Snow emerged a changed woman—and became the villain Killer Frost. Sociopathic by nature, Killer Frost’s icy exterior matches her chillingly cold interior. Militant and sadistic, she enjoys killing and feels no remorse when taking another’s life."],
["laufey", "Laufey", "marvel", "39", "King of Jotunheim and father of God of Mischief – Loki. Laufey is a Frost Giant with super strength and a huge army, enough to conquer th Earth."],
["lex luther", "Lex Luther", "dc", "34", "A self-made man whose immeasurable intellect is always in conflict with his equally immeasurable ego, Lex Luthor is one of the world's most brilliant minds and most famous villains. From a young age, Lex utilized his almost unparalleled acumen to build himself a financial empire through hard work and dedication—but mainly through the strategic use of intimidation, bribery and murder. Driven by jealousy masked with hate over what he perceives to be his stolen place as humanity's true savior, Luthor constantly attempts to destroy and humiliate Superman at every possible opportunity."],
["lobo", "Lobo", "dc", "31", "Lobo is a ‘Czarnian’ with exceptional strength and fortitude. He enjoys nothing better than mindless violence and intoxication, and killing is an end in itself; his name roughly translates as \"he who devours your entrails and thoroughly enjoys it.\""],
["loki", "Loki", "marvel", "40", "Loki, Prince of Asgard, Odinson, rightful heir of Jotunheim, and God of Mischief, is burdened with glorious purpose. His desire to be a king drives him to sow chaos in Asgard. In his lust for power, he extends his reach to Earth."],
["lucifer", "Lucifer", "dc", "96", "Lucifer Morningstar was once a proud and the most beautiful of all the angels. As discussed above, Yahweh created two brothers (Samael being the eldest). Yahweh had instructed and guided them on how to use their powers to form creation, known as the DC Multiverse."],
["lucifer morningstar", "Lucifer Morningstar", "dc", "96", "Lucifer Morningstar was once a proud and the most beautiful of all the angels. As discussed above, Yahweh created two brothers (Samael being the eldest). Yahweh had instructed and guided them on how to use their powers to form creation, known as the DC Multiverse."],
["magneto", "Magneto", "marvel", "37", "Harnessing his powerful magnetic abilities, he has become a radical freedom fighter in the name of his kind. His only priority is the preservation of the mutant race—even at the expense of what some might deem to be the greater good."],
["magnus", "Magnus", "marvel", "78", "Emerging from a cocoon, the being known as Adam Warlock defies his creators' intentions and proves to be an important cosmic entity. Created by the Enclave to be part of a race of super humans who would abolish war, illness, and crime, Adam Warlock is a unique being who uses his immense and formidable powers to safeguard the universe."],
["man of steel", "Man of Steel", "dc", "70", "Faster than a speeding bullet, more powerful than a locomotive… The Man of Steel fights a never-ending battle for truth, justice, and the American way. From his blue uniform to his flowing red cape to the \"S\" shield on his chest, Superman is one of the most immediately recognizable and beloved DC Super Heroes of all time. The Man of Steel is the ultimate symbol of truth, justice, and hope. He is the world's first Super Hero and a guiding light to all."],
["martian manhunter", "Martian Manhunter", "dc", "71", "J’onn J’onzz of the planet Mars was accidentally transported to Earth, where he became one of its greatest champions under the moniker Martian Manhunter. Displaying a vast array of powers that can give even Superman a run for his money, the Martian Manhunter was a founding member of the Justice League of America, and has been a member of almost every incarnation of the League ever since. One of the last surviving members of his species, the Martian Manhunter wields such powers as the ability to shape-shift, telepathy, flight, invisibility, phasing, super-strength and Martian vision. His only weakness in an inherent fear of fire, which all Martians have."],
["michael demiurgos", "Michael Demiurgos", "dc", "97", "Before any life, even before the DC Multiverse existed, Yahweh the Almighty created two brothers. Alongside his twin brother to Samael, Michael Demiurgos is said to be accredited for the creation of the DC Multiverse."],
["mr fantastic", "Mr Fantastic", "marvel", "21", "Reed Richards just might be the smartest person on the planet. As the Fantastic Four’s resident genius, Reed finds that his teammates depend on him for leadership and direction; and while he’s been known to get caught up in the scientific analysis of a situation, he always comes through for his team when it counts. And ye he is the man who can strech any of his body part as much as he wants."],
["mr miracle", "Mr Miracle", "dc", "71", "Raised on Apokolips, Scott Free experienced near constant pain and suffering throughout his early life. However, despite the brutality and violence inflicted upon him, his will never broke and he never gave up hope. He dreamed of escape. But to escape the unescapable, he would need a miracle—so he became Mister Miracle."],
["mr mxyzptlk", "Mr Mxyzptlk", "dc", "89", "Hailing from the 5th Dimension, Mr. Mxyzptlk appears as an imp, fashioned as a jester of some sort. While he has the power to do almost anything he is able to imagine, such as erasing any being from existence, he takes no pleasure or fun in that. Instead, he often seeks amusement, which sees him challenge Superman."],
["nebula", "Nebula", "marvel", "14", "The fierce warrior Nebula is the adopted daughter of Thanos and the “sister” of Gamora. As the Mad Titan raised his “daughters,” he trained the two in combat, often forcing them to face off against each other. As a pirate and mercenary with her intentions set on conquering other empires, this daughter of Thanos is feared by many across the star systems."],
["nick fury", "Nick Fury", "marvel", "1", "Years ago, Fury worked closely with spy Clint Barton (a.k.a. Hawkeye) to develop S.H.I.E.L.D., a worldwide high-tech security organization; however, S.H.I.E.L.D.'s directorship itself went to Fury's commanding officer, General Ross. Fury participated in the Gulf War, during which he lost an eye and the mutant adventurer Wolverine saved his life."],
["nova", "Nova", "marvel", "77", "When the space pirate Nebula destroyed the planet Xandar, its World-Mind transferred the deceased Nova Corps’ collective Nova-Force into their sole survivor, Garthan Saal, to safeguard the energies and distribute them to worthy successors of Xandar’s noble tradition. Saal was transformed into the immensely powerful Super-Nova, but the energies drove him mad."],
["odin", "Odin", "marvel", "82", "Odin the monarch of Asgard and the strongest of all Asgardians, even his son Thor. He can manipulate magic for a variety of effects including strength augmentation,size augmentation, various magical enchantments, fire energy blasts, and others."],
["one above all", "One Above All", "marvel", "99", "The creator of Marvel world with complete omnipotence. Well, it sometimes represent the writers of Marvel."],
["phoenix force", "Phoenix Force", "marvel", "91", "Phoenix Force is the most feared being in the universe. Single handedly defeated Galactus himself and over powered even the mkraan crystal."],
["poison ivy", "Poison Ivy", "dc", "2", "Once an innovative, radical botanical biochemist named Pamela Isley, Poison Ivy’s academic ambitions died on the vine when she was subjected to less-than-reputable experiments. These tests twisted Isley’s mind and gave her a dangerous set of superpowers. Ivy found herself able to control plants and began to use her wiles and pheromones to mesmerize and manipulate people. She entrances them into doing her bidding and then draws them in, where they soon discover Ivy’s other power: her kiss and touch can be lethal."],
["powergirl", "Powergirl", "dc", "67", "She is supergirl from another world. With all her powers and abilities she can go toe to toe with superman too."],
["prashant", "Prashant", "", "100", "Meet your developer. Stan Lee of this app. In this world he is the completely omnipotent being with unlimited power in every sense."],
["presence", "Presence", "dc", "99", "He is the representative of god in DC world with complete omnipotence."],
["professor x", "Professor X", "marvel", "58", "Charles Xavier is one of the world's premiere experts on mutants. A mutant telepath, Charles and his wife Moira MacTaggert wrote the book on post-human medicine, treating young mutants endangered by their own powers."],
["punisher", "Punisher", "marvel", "4", "Frank Castle was an honest ex-Marine with a family he loved. But when that family was murdered, he became a vigilante with a uniquely brutal brand of justice."],
["quicksilver", "Quicksilver", "marvel", "25", "Pietro and his sister Wanda were living a quiet life in the Transian countryside with their adoptive family when their true father came back into their lives. Magneto informed them they were mutants and offered his children a place by his side. He told them of his goal to teach the world about the now emerging mutantkind and of his dream of mutants and humans living side by side. "],
["ra’s al ghul", "Ra’s Al Ghul", "dc", "4", "Independently wealthy. Utilizes his vast fortune to finance and further his goals. Incredibly intelligent. A brilliant strategist. Master martial artist. Allied with a host of expert warriors under his command.  No, we’re not talking about Batman, but a man who has proven to be one of his most dangerous and destructive adversaries. He is Ra’s al Ghul, the Demon’s Head, leader of the League of Assassins and the only person in the world capable of going toe-to-toe with the Bat on every level."],
["raven", "Raven", "dc", "52", "Raven is the daughter of the interdimensional demon Trigon, a malicious and powerful being that seeks to conquer and enslave the people of Earth—and whose dark powers and influence were passed down to his daughter. Raised in the alternate dimension of Azarath, the half-human, half-demon. Raven is extremely powerful, gifted with magical, psychic and telekinetic powers as well as the ability to manipulate energy, emotion and shadows."],
["red hood", "Red Hood", "dc", "2", "The Red Hood is an alias used by multiple characters and a criminal organization in DC World. Jason Todd is the most widely known character to use this persona."],
["reverse flash", "Reverse Flash", "dc", "27", "For every action, there's an equal and opposite reaction. And with every step the Flash takes toward the future, someone from the future is racing backward through time to stop him—the villainous speedster known as the Reverse-Flash. Born in the 25th Century, Eobard Thawne grew up idolizing the Flash and studying the legacy of the Scarlet Speedster. However, as he learned more about the Flash, Eobard discovered how his own life was linked to his hero’s: He was destined to become one of Barry Allen’s greatest villains, a revelation that led Eobard to grow unhinged."],
["riddler", "Riddler", "dc", "1", "One of the Dark Knight's most infamous villains, Edward Nygma enjoys flaunting his intellectual superiority by conducting crimes and leaving clues for Batman to piece together. While this habit constantly leads to the aptly named Riddler failing in his criminal endeavors, his puzzle-problem actually stems not only from his own narcissism and ego, but also from a deep-seeded psychological compulsion."],
["robin", "Robin", "dc", "9", "Every kid wants to be Batman, but do you have a lifetime of training? A billion-dollar fortune? The dream gets dashed pretty quickly. So OK, maybe you can’t be Batman… but that doesn’t mean you can’t be adopted by him. And just like that, Robin the Boy Wonder made the kid sidekick an icon."],
["rocket", "Rocket", "marvel", "12", "As the weapons and tactical expert of the Guardians of the Galaxy, Rocket risks his hide to defend the cosmos. Ain’t no thing like Rocket, ‘cept Rocket. He lives for the simple things, including collecting valuable bounty alongside his friend and partner, Groot. Quick to train a weapon on anyone who offends him, he’s far more formidable than he appears."],
["rocket raccoon", "Rocket Raccoon", "marvel", "12", "As the weapons and tactical expert of the Guardians of the Galaxy, Rocket risks his hide to defend the cosmos. Ain’t no thing like Rocket, ‘cept Rocket. He lives for the simple things, including collecting valuable bounty alongside his friend and partner, Groot. Quick to train a weapon on anyone who offends him, he’s far more formidable than he appears."],
["ronan", "Ronan", "marvel", "57", "As a cruel and fanatical member of the Kree race, Ronan double-crossed Thanos in an attempt to keep the Power Stone for himself. The genocidal Ronan will stop at nothing to advance he agenda of the Kree Empire, even if it means violating a peace treaty and wiping out all Xandarians using the Power Stone."],
["savitar", "Savitar", "dc", "28", "Savitar is God of Speed. Savitar can move at super-speed, and is able to lend or steal speed from moving objects. He has accelerated healing due to increased metabolism and can generate a full Inertia force field."],
["scarecrow", "Scarecrow", "dc", "3", "As a young child, Jonathan Crane was subjected to sick and twisted experiments on fear conducted by his own father. Emotionally scarred and mentally unstable from the ordeal, Crane spent his childhood living in fear until he made an important realization—if he could control fear, it would never again control him. Over time, this interest in fear become an obsession. Graduating from college with a doctorate in psychology and specialty in phobias, Jonathan began experimenting on others, subjecting them to a hallucinogenic fear toxin he developed that brought out their worst nightmares."],
["scarlet witch", "Scarlet Witch", "marvel", "54", "Notably powerful, Wanda Maximoff has fought both against and with the Avengers, attempting to hone her abilities and do what she believes is right to help the world."],
["scorpion", "Scorpion", "marvel", "3", "Carmilla Black is a genetically engineered human, created by Advanced Idea Mechanics (A.I.M.). Though A.I.M. Scientist Supreme Monica Rapuccini considers her a daughter, she grew up with adoptive parents, who were also agents of A.I.M., never knowing of her or their involvement with the organization. Carmilla considered herself a normal teen until her latent powers manifested on the night of her prom. Her mutated arm, which she has taken to calling her stinger, discharged a highly concentrated dosage of toxins, killing her boyfriend."],
["shazam", "Shazam", "dc", "74", "When Billy Batson speaks the name of an ages-old wizard, he is transformed into the World's Mightiest Mortal—Shazam!"],
["she hulk", "She Hulk", "marvel", "43", "After getting a blood transfusion from her cousin Bruce Banner, Jennifer Walters gained all the powers of the Hulk – and all the problems. But while she gained massive strength, she never lost her passion for justice."],
["silver surfer", "Silver Surfer", "marvel", "81", "One of the noblest and most tormented cosmic entities in the universe, the Silver Surfer treasures freedom above all else, but has often sacrificed his liberty for the greater good. He was born Norrin Radd on the planet Zenn-La, part of an extremely long-lived and technologically advanced humanoid race which had created a worldwide utopia devoid of crime, disease, hunger, poverty, and want of any kind. Convincing a Council of Scientists member to provide him with a spaceship, Radd soon confronted the invader, Galactus, who intended to consume Zenn-La. Radd offered to become his herald and seek out new worlds for him in exchange for Galactus sparing Zenn-La. "],
["sinestro", "Sinestro", "dc", "60", "\"In blackest day, in brightest night, beware your fears made into light. Let those who try to stop what's right, burn like my power, Sinestro's might!\" From the greatest Green Lantern to the Corps' greatest enemy, Thaal Sinestro's fall from grace can easily be attributed to his own hubris—but if you ask him, the real problem lies in the Green Lantern Corps itself and its creators, the Guardians of the Universe. After all, as far as Sinestro is concerned, everything he does is for the good of the universe."],
["skaar", "Skaar", "marvel", "53", "Skaar is the son of The Hulk in an alternate reality. He possesses powers similar to his father, but greater. His physical strength is so high, that he cracked the armor of the Juggernaut and sent him into the outer atmosphere with one punch, which is something that was considered impossible and that even his father failed to do."],
["solomon grundy", "Solomon Grundy", "dc", "49", "“Solomon Grundy, born on a Monday…”  The undead monster known as Solomon Grundy is powerful, immortal and bad news for every hero unfortunate enough to cross his path. Grundy was a corrupt man named Cyrus Gold until his untimely death in Slaughter Swamp. Since then, his entire existence has been an unending cycle of death and rebirth. When Grundy dies, he eventually rises again, emerging from the depths of his original resting place in the swamp to wreak havoc on the living."],
["spectre", "Spectre", "dc", "95", "The Spectre is an aspect of The Presence, God’s Vengeance. After creation, Lucifer led the rebellion of the angels against The Presence, one of whom was the angel Raguel/Aztar. Aztar later repented of his sins and, in return, was stripped of his memories and became the incarnation of His Wrath."],
["spider man", "Spider Man", "marvel", "22", "Bitten by a radioactive spider, Peter Parker’s arachnid abilities give him amazing powers he uses to help others, while his personal life continues to offer plenty of obstacles."],
["spiderman", "Spider Man", "marvel", "22", "Bitten by a radioactive spider, Peter Parker’s arachnid abilities give him amazing powers he uses to help others, while his personal life continues to offer plenty of obstacles."],
["spider-man", "Spider Man", "marvel", "22", "Bitten by a radioactive spider, Peter Parker’s arachnid abilities give him amazing powers he uses to help others, while his personal life continues to offer plenty of obstacles."],
["starlord", "Starlord", "marvel", "56", "Leader of the Guardians of the Galaxy, Peter Quill, known as Star-Lord, brings a sassy sense of humor while protecting the universe from any and all threats."],
["steppenwolf", "Steppenwolf", "dc", "67", "Every tyrannical warlord needs a general they can trust, and luckily for Darkseid, he need not look further than his uncle, Steppenwolf. As one of the immortal New Gods, Steppenwolf's capacity for violence is nearly unmatched throughout the galaxy."],
["storm", "Storm", "marvel", "13", "As a storied, veteran X-Men member, Ororo Munroe - aka Storm - is one of the most powerful mutants on Earth. A trusted and wise leader of the team, with the ability to control and manipulate weather patterns, Storm has created a legacy."],
["submariner", "Submariner", "marvel", "36", "It is widely believed Namor was the world's first mutant hero. He first appeared in 1939, off the cost of Southampton, New York. Namor encountered two humans in diving suits and, seeing they were in danger, he helped them to the surface.  Discovering a new world outside the vast sea, Namor began to explore. He found a world at war. Namor joined the Allies' super soldiers, the Invaders, and helped them defeat the Axis powers in Europe"],
["super girl", "Super Girl", "dc", "68", "As the most powerful teenager on the planet, the Girl of Steel possesses all of Superman’s powers—from superhuman strength, speed, and invulnerability all the way down to his flight and enhanced senses."],
["superboy", "Superboy", "dc", "33", "Superboy, also known as Kon-El and Conner Kent, was a DNAlien designed to replace Superman after the hero's death touted as Superman's direct clone."],
["superman", "Superman", "dc", "70", "Faster than a speeding bullet, more powerful than a locomotive… The Man of Steel fights a never-ending battle for truth, justice, and the American way. From his blue uniform to his flowing red cape to the \"S\" shield on his chest, Superman is one of the most immediately recognizable and beloved DC Super Heroes of all time. The Man of Steel is the ultimate symbol of truth, justice, and hope. He is the world's first Super Hero and a guiding light to all."],
["superman prime", "Superman Prime", "dc", "93", "Superman Prime is a version of Superman in the future. After living inside the Earth’s yellow sun for 15,000 years, the Man of Steel enhanced his powers to great cosmic levels, giving him nigh-omnipotence, invulnerability, and the ability to create life and entire universes."],
["swamp thing", "Swamp Thing", "dc", "11", "The monstrous Swamp Thing can control every iota of plant life on this planet, from the fungus on stale bread to forests of towering oaks. Superhumanly strong and grotesque, he can grow himself a full array of titanic bodies from even the tiniest sprout of green. A living embodiment of the power and terror in our environment, the Swamp Thing protects both humanity and the environment—usually from each other."],
["thanos", "Thanos", "marvel", "64", "The Mad Titan Thanos quests across the universe in search of the Infinity Stones, intending to use their limitless power for shocking purposes. Using the power of the Infinity Stones, Thanos believes he can ultimately save the universe by wiping out half of its population."],
["thanos with infinity gauntlet", "Thanos with Infinity Gauntlet", "marvel", "84", "The Mad Titan Thanos quests across the universe in search of the Infinity Stones, intending to use their limitless power for shocking purposes. Using the power of the Infinity Stones, Thanos believes he can ultimately save the universe by wiping out half of its population."],
["the living tribunal", "The Living Tribunal", "marvel", "96", "The living tribunal is considered the second strongest being in the marvel universe second only to the one above all (and later on, The Beyonder). The living tribunal is the supreme authority in the marvel universe save The One Above All. His power is absolutely limitless.  "],
["the thing", "The Thing", "marvel", "24", "Gruff and gung-ho Ben Grimm rocks the Marvel Universe as the rocky Thing, a powerhouse with a heart of gold and the backbone of the Fantastic Four. With his nearly-indestructible body and incredible strength and stamina, the Thing possess the ability to defend the innocent and crush evil, but also to help the Fantastic Four explore the unknown throughout the multiverse. "],
["thing", "Thing", "marvel", "24", "Gruff and gung-ho Ben Grimm rocks the Marvel Universe as the rocky Thing, a powerhouse with a heart of gold and the backbone of the Fantastic Four. With his nearly-indestructible body and incredible strength and stamina, the Thing possess the ability to defend the innocent and crush evil, but also to help the Fantastic Four explore the unknown throughout the multiverse. "],
["thor", "Thor", "marvel", "66", "The son of Odin uses his mighty abilities as the God of Thunder to protect his home Asgard and planet Earth alike. Thor Odinson wields the power of the ancient Asgardians to fight evil throughout the Nine Realms and beyond. "],
["trickster", "Trickster", "dc", "1", "Once an average circus performer, the Trickster turned to a life of crime when he invented shoes that allowed him to hover. He soon became an enemy of the Flash. In Justice League: Unlimited, it was hinted that the Trickster may have a disorder that impairs his judgment since the Flash noted that he is off his medication."],
["ultron", "Ultron", "marvel", "60", "The creation gone awry, the sentient robot Ultron hates and seeks to wipe out humanity. An artificial intelligence with access to all the data in the world, Ultron decides that the best way to save the Earth is to destroy all the people on it to make way for a new race of highly intelligent robotic lifeforms."],
["valkyrie", "Valkyrie", "marvel", "48", "Gifted the power of the legendary Asgardian Brunnhilde, Parrington assumed the mantle and the cosmic responsibilities of the Valkyrie. Valkyrie uses her superhuman strength to defend Asgard."],
["venom", "Venom", "marvel", "31", "When Spider-Man acquired a living symbiote costume, he had no idea that it would later spawn a major adversary. Though it often acts as a foe to the Wallcrawler, Venom does possess some kind of morality—avoiding harm to the innocent and bringing down the bad peoples."],
["vibe", "Vibe", "dc", "14", "Cisco Ramon was caught in the event horizon of a boom tube during Darkseid's first invasion of Earth. The exposure to the interdimensional forces rewrote his DNA, and now Cisco uses his vibrational powers to help A.R.G.U.S. find and restrain dangerous fugitives from other realities. The second-youngest member of the Justice League of America, he is the hero known as Vibe."],
["vision", "Vision", "marvel", "66", "A fully unique being, Vision came about thanks to a combination of Wakandan Vibranium, Asgardian lightning, an Infinity Stone, and more. Vision defies physics and fights as an Avenger with the power of density manipulation and his flawless computer brain."],
["vulcan", "Vulcan", "marvel", "79", "He is an omega level mutant. He has the ability to manipulate all forms of energy at will and can absorbs them as well, even magic. "],
["wanda", "Wanda", "marvel", "52", "Notably powerful, Wanda Maximoff has fought both against and with the Avengers, attempting to hone her abilities and do what she believes is right to help the world."],
["wasp", "Wasp", "marvel", "19", "While the lost daughter of Hank Pym inherits his scientific mind, Nadia Pym follows in the footsteps of her step-mother Janet van Dyne to carve out a place for herself in the Super Hero community as the Unstoppable Wasp. "],
["winter soldier", "Winter Soldier", "marvel", "17", "James Buchanan “Bucky” Barnes enlists to fight in World War II, but eventually literally falls in battle. Unfortunately, the evil Arnim Zola recovers him and erases his memory, turning him into a highly-trained assassin called the Winter Soldier."],
["wolverine", "Wolverine", "marvel", "33", "From the northern wilderness of Canada hails one of the gruffest, most irascible, totally cynical and brooding member of the X-Men ever to grace the team with his presence. A mutant with an unstoppable healing power, adamantium metal claws and no-nonsense attitude makes the man called Logan, one of the most ferocious heroes in the universe."],
["wonder woman", "Wonder Woman", "dc", "65", "Beautiful as Aphrodite, wise as Athena, swifter than Hermes, and stronger than Hercules, Princess Diana of Themyscira fights for peace in Man's World."],
["zatanna", "Zatanna", "dc", "52", "With a name like Zatanna Zatara, becoming a professional stage magician almost seems like an unquestionable career choice. Of course, it doesn’t hurt that the illusions she creates and the spells she weaves to dazzle the audience just so happen to be real. By reciting spells backwards, she can invoke anything her imagination wills, and her inventiveness often allows her to find creative solutions to even the trickiest of problems."],
["zod", "Zod", "dc", "70", "Once Krypton’s greatest military leader, General Dru-Zod was banished to the Phantom Zone for crimes he committed against the people of Krypton. Trapped for years—long past the destruction of his home planet—Zod emerged from his interdimensional prison seeking revenge against the man he blamed for his captivity by going after his jailer’s surviving son: Kal-El of Krypton, the hero known as Superman."],
["zoom", "Zoom", "dc", "27", "Zoom is utterly unlike the Flash and other speedsters, both setting him apart and making him one of the most dangerous and challenging of Flash’s foes. His speed doesn’t come from the Speed Force, but from altering his own relative time, slowing or speeding up the world around him, allowing him to run even faster than the Flash. His warped sense of heroism and villainy has led Zoom to continuously threaten not only those closest to the Flash but also countless heroes throughout the DC Universe."]
]

    var promt = [" Hope you are having fun!! You can go for other round or can say bye."]
    var total_characters = characters.length;
    var rawInput = input.toLowerCase() ;
    var p = rawInput.toString().split(' and ');
    if (rawInput ==='bye' || rawInput==='exit') {
        return conv.close('Well that was quite a fight. I think they need some rest and so do you. Byee! See you soon!!');
    }
    if(typeof(p[1])==="undefined")
    {
        p = rawInput.split(' vs ');
    }
    if(typeof(p[1])==="undefined")
    {
        p = rawInput.split(' versus ');
    }
    if(typeof(p[1])==="undefined")
    {
        p = rawInput.split(' - ');
    }
    if(typeof(p[1])==="undefined")
    {
        p = rawInput.split(' against ');
    }
    if(typeof(p[1])==="undefined")
    {
        for(var i = 0; i<total_characters; i++){
            if(rawInput === characters[i][0]){
                var s = parseInt(characters[i][3]);
                s = (s - s%10)/10;
                return conv.ask('<speak>' + characters[i][4] + '<break time="1"/>On a scale of 10 ' + characters[i][1] + ' is ' + (s+1) + '.<break time="1"/>'+ promt[0] + '</speak>');
            }
        }
        return conv.ask('<speak>Enter two names or cleary mention a seperator like \'vs\', \'versus\', \'against\' or atleast \'-\' (hyphen).' + '</speak>');
    }
    if(typeof(p[3])!=="undefined")
    {
        conv.ask('<speak>Unusual names. I must say. Try something simpler.</speak>');
    }

    var s1 = -1, s2 = -1, ans;
    for(i = 0; i<total_characters;i++){
        if(characters[i][0] === p[0]){
            s1=parseInt(characters[i][3]);
            var winner = characters[i][1];
        }
        if(characters[i][0] === p[1]){
            s2=parseInt(characters[i][3]);
            var loser = characters[i][1];
        }
    }

    if(s1 === -1){
        return  conv.ask('<speak>Is ' + p[0] + ' a real character? I doubt so. Maybe I need to do a research on him. Till then try someone else.</speak>');
    }
    if(s2 === -1){
        return  conv.ask('<speak>Are you serious? I haven\'t heard of him. ' + p[1] + ' doesn\'t ring a bell to me. But you can try another characters.</speak>');
    }

    var diff = s1 - s2;

    if( diff < 0){
        diff *= -1;
        var t = winner;
        winner = loser;
        loser = t;
    }

    diff = diff/10;

    if(winner === loser){
        return  conv.ask('<speak>Well this would be a good fight only if you manage to bring two of ' + winner + '. The match may even go on forever.<break time="1"/>' + promt[0] + '</speak>');
    }
    if(diff < 2){
        return  conv.ask('<speak>Well this is a tough one, I guess. Fight may last long but eventually ' + winner + ' will take down ' + loser + '.<break time="1"/>' + promt[0] + '</speak>');
    }
    if(diff < 4){
        return  conv.ask('<speak>I say this one is easy. Odds and power all with the ' + winner + '. No doubt in it, ' + winner + ' will win for sure.<break time="1"/>' + promt[0] + '</speak>');
    }
    else {
        return  conv.ask('<speak>I don\'t think this is even a match. Its like big bully vs an infant. ' + winner + ' may not even sweat.<break time="1"/>' + promt[0] + '</speak>');
    }

});

exports.myfunction = functions.https.onRequest(app);
